### ISSUE TITLE
To Do list for HTML5 sim pages design team

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#100]
- [x] redesign tables of activities
  - [x] update default sorting behavior
- [x] redesign tables of translated sims 
- [x] design link to legacy activities if no html5 activities available
- [x] improve teacher tips discoverability 
- [x] new registration page (#94) 
- [x] "new sims" should be all html5 sims (#82)
- [x] clean up activity submission page (https://github.com/phetsims/website/issues/102)

**Comment by amanda-phet** [comment]
Here is our mockup for addressing three of the above checklist items. 
To improve discoverability of Teacher Tips, we've separated it from the Video Primer section, changed the text, and added a PDF icon. Clicking the PDF icon should behave the same as clicking the PDF text (opens the PDF in a new tab). 

![screen shot 2015-03-19 at 1 01 09 pm](https://cloud.githubusercontent.com/assets/7852916/6738482/0e134aac-ce38-11e4-8c57-eb5c0201e190.png)

We changed the title from Activities to Activities and Resources since some of the files are course outlines and things of that nature. The column titles can be clicked to sort the table (just as the current version behaves). The Share an Activity button brings them to the appropriate page *with the sim filled in*. 

![screen shot 2015-03-19 at 1 03 15 pm](https://cloud.githubusercontent.com/assets/7852916/6738522/5634291e-ce38-11e4-9399-e146cf8f58b2.png)

The translations table has a similar look to the one above but the column titles can not be clicked. The button to Translate This Sim brings them to https://phet-dev.colorado.edu/en/for-translators/translation-utility and the for translators link brings them to https://phet-dev.colorado.edu/en/for-translators. 
![screen shot 2015-03-19 at 1 05 05 pm](https://cloud.githubusercontent.com/assets/7852916/6738614/d50353d2-ce38-11e4-93d0-af1c4b61b405.png)

Colors, the darker ones being the same color of the title row and horizontal lines in each table: 
![screen shot 2015-03-19 at 1 07 53 pm](https://cloud.githubusercontent.com/assets/7852916/6738636/f921d1b2-ce38-11e4-999a-efa8316a6187.png)

When designing the tables, we kept in mind guidelines for accessibility, which seem very important for the developer: http://webaim.org/techniques/tables/data.

**Comment by amanda-phet** [comment]
The sorting for activities will be similar to the original with one slight change: 
1. Locale
2. Gold Star
3. Date *updated*
