### ISSUE TITLE
To do list for HTML5 sim pages

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#101]
- [x] Screenshots with HTML5 aspect ratio (https://github.com/phetsims/tasks/issues/132)
- [x] QA testing
 - [x] make sure website works in different locale
- [x] user/teacher testing 
- [x] platform for video primers (https://github.com/phetsims/tasks/issues/181)
- [x] sort through activities and tag compatible ones (https://github.com/phetsims/tasks/issues/194)
 - [ ] get in touch with activity authors 
- [x] Registration page (#94) 
- [x] Activity Submission page 
 - [x] Licensing agreement
- [x] Terms of Use (not sure if it is necessary for the roll out)

**Comment by zepumph** [comment]
@amanda-phet this looks like it can be closed, is that correct?

**Comment by amanda-phet** [comment]
yes Trish/Steele emailed the gold-star authors so I think that is good enough. Closing.
